version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
