name: smart_broccoli
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  collection: ^1.14.13
  device_calendar: ^3.1.0
  email_validator: ^1.0.5
  firebase_core: ^0.5.1
  firebase_messaging: ^8.0.0-dev.5
  fluro: ^1.7.3
  flutter_local_notifications: ^3.0.1+2
  flutter_settings:
    git:
      url: https://github.com/comp90018-2020/Flutter-settings.git
  flutter_svg: ^0.19.1
  geocoding: ^1.0.5
  geolocator: ^6.1.0
  http: ^0.12.2
  image: ^2.1.18
  image_picker: ^0.6.7+11
  light: ^1.0.0
  numberpicker: ^1.2.1
  package_info: ^0.4.3
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  provider: ^4.3.2
  quiver: ^2.1.4
  selection_picker:
    git:
      url: https://github.com/comp90018-2020/selection_picker.git
  sensors: ^0.4.2+6
  shared_preferences: ^0.5.12
  socket_io_client: ^0.9.11
  sqflite: ^1.3.0
  url_launcher: ^5.7.4
  wifi_info_plugin: ^1.1.5
  workmanager: ^0.2.0
  xml: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  # the below package was used to generate launcher icons
  # flutter_launcher_icons: "^0.8.0"

# Icon configuration for flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "LOGO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/account_circle-black-24dp.svg
    - assets/posing_broccoli.png

    # Licenses
    - assets/licenses/material_design_icons
    - assets/licenses/patrick_hand
    - assets/licenses/auto_size_text
    - assets/licenses/collection
    - assets/licenses/device_calendar
    - assets/licenses/email_validator
    - assets/licenses/firebase
    - assets/licenses/fluro
    - assets/licenses/flutter
    - assets/licenses/flutter_local_notifications
    - assets/licenses/flutter_plugins
    - assets/licenses/flutter_settings
    - assets/licenses/flutter_svg
    - assets/licenses/geocoding
    - assets/licenses/geolocator
    - assets/licenses/http
    - assets/licenses/image
    - assets/licenses/image_picker
    - assets/licenses/light
    - assets/licenses/numberpicker
    - assets/licenses/permission_handler
    - assets/licenses/provider
    - assets/licenses/quiver
    - assets/licenses/selection_picker
    - assets/licenses/socket_io_client
    - assets/licenses/sqflite
    - assets/licenses/wifi_info_plugin
    - assets/licenses/workmanager
    - assets/licenses/xml

  fonts:
    - family: PatrickHandSC
      fonts:
        - asset: assets/fonts/PatrickHandSC-Regular.ttf
