name: smart_broccoli
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  collection: ^1.14.13
  device_calendar: ^3.1.0
  email_validator: ^1.0.5
  fluro: ^1.7.3
  flutter_svg: ^0.19.1
  geocoding: ^1.0.5
  geolocator: ^6.1.0
  http: ^0.12.2
  image_picker: ^0.6.7+11
  light: ^1.0.0
  numberpicker: ^1.2.1
  package_info: ^0.4.3
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  provider: ^4.3.2
  quiver: ^2.1.4
  sensors: ^0.4.2+6
  shared_preferences: ^0.5.12
  socket_io_client: ^0.9.11
  sqflite: ^1.3.0
  url_launcher: ^5.7.4
  wifi_info_plugin: ^1.1.5
  workmanager: ^0.2.0
  xml: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# Icon configuration for flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "LOGO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/account_circle-black-24dp.svg

  fonts:
    - family: PatrickHandSC
      fonts:
        - asset: assets/fonts/PatrickHandSC-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
