version: '3'
services:
  watchtower:
    image: index.docker.io/containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
  web:
    image: registry.steventang.net/comp90018/backend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PORT=3000
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - TOKEN_SECRET
      - FIREBASE_PRIVATE_KEY
      - FIREBASE_PROJECT_ID
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_DATABASE_URL
    volumes:
      - ./data/uploads:/app/uploads
    links:
      - postgresql
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    restart: always
  caddy:
    image: "caddy:latest"
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
      - 80:80/udp
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt/live/fuzzybroccoli.com/fullchain.pem:/etc/certs/cert.pem
      - /etc/letsencrypt/live/fuzzybroccoli.com/privkey.pem:/etc/certs/key.pem
      - ./log:/var/log
