name: Build app

on:
  push:
    branches-ignore:
      - 'backend*'

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '14.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - run: zip -9 -r source.zip .
      if: github.ref == 'refs/heads/master'

    - name: Check formatting
      run: flutter format lib/ && git diff --exit-code

    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test

    - run: flutter build apk 2>&1 | tee compile.txt
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dependabot/gradle/android')

    - if: github.ref == 'refs/heads/master'
      run: |
        sudo apt-get install -y pango1.0
        pango-view --font=mono -qo compile.png compile.txt

    - run: git log > commit_logs.txt
      if: github.ref == 'refs/heads/master'

    - run: cp build/app/outputs/apk/release/app-release.apk app.apk
      if: github.ref == 'refs/heads/master'

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: "Group W01_10-4 Programming Project Submission"
        path: |
          app.apk
          compile.png
          commit_logs.txt
          submission.txt
          contributions.pdf
          source.zip
