name: Fuzzy Broccoli

on:
  push:
    branches-ignore:
      - 'backend*'

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '14.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20'

    - name: Check formatting
      run: flutter format lib/ && git diff --exit-code

    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test

    - run: flutter build apk
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dependabot/gradle/android')

    - name: Save artifacts
      uses: actions/upload-artifact@v1
      if: github.ref == 'refs/heads/master'
      with:
        name: apk
        path: build/app/outputs/apk/release/app-release.apk
